#!/usr/bin/env zsh
# config for devuan-live.blend

arrs+=(custom_deb_packages)

blend_name="devuan-live-sample"
blend_vers="1.0"
image_name="${blend_name}-${blend_vers}-${arch}"

loginname="devuan"
password="devuan"
user_default_shell="/bin/bash"
rootcredentials="root:devuan"

# Not yet implemented.
# grub_version=""		# grub-pc or grub-efi-amd64   



# Use a trailing slash for rsync.
# custom system files go in rootfs_overlay.
# isolinux boot splash, boot help files go in isolinux_overlay

rootfs_overlay="$R/extra/rootfs/"
isolinux_overlay="$R/extra/isolinux/"


extra_packages+=(

	live-config
	live-config-sysvinit
	syslinux
	syslinux-common
	isolinux
	rsync
	squashfs-tools
	xorriso
	cryptsetup
)



# Packages in live-sdk/extra/custom-packages
# These will be installed in the following order:
custom_deb_packages+=(
	refracta-lang_1.1.deb
	refractainstaller-base_9.2.1_all.deb
	refractasnapshot-base_10.0.2_all.deb
)
	
