#!/usr/bin/env zsh
# config for jessie-oblx.blend

vars+=(username userpass default_shell efi_work)
arrs+=(custom_deb_packages)

blend_name="jessie-oblx"
blend_vers="1.0"
os="$blend_name"

image_name="${blend_name}-${blend_vers}-${arch}"

os="$blend_name"
release="jessie"


username="user"
userpass="user"
default_shell="/bin/bash"
rootcredentials="root:root"


# If you don't want uefi, comment out this line
# and line 30 of jessie-oblx.blend, and change
# grub-efi-amd64 below to grub-pc
efi_work="$R/extra/efi-files"


#####  To exclude recommends: lines 101 and 161 in zlibs/bootstrap.

base_packages+=(grub-efi-amd64)

extra_packages+=(

	sshfs
	mbr
	w3m
	hwinfo
	moc
	libav-tools
	ntfs-3g
	dosfstools
	live-config
	live-config-sysvinit
	squashfs-tools
	xorriso
	pmount
	pv
	rsync
	syslinux
	syslinux-common
	isolinux
	gdisk
	irssi
	scrot
	feh
	p7zip-full
	pm-utils
	sysv-rc-conf
	tree
	file
	live-boot-doc
	live-config-doc
	dkms
	eject
	openssh-blacklist
	xorg 
	xserver-xorg
	xinit
	xserver-xorg-video-all
	xterm
	openbox
	openbox-menu
	obconf
	lxappearance
	lxappearance-obconf
	lxpanel
	lxterminal
	lxrandr
	spacefm
	xarchiver
	libnotify-bin
	mesa-utils
	gparted
	leafpad
	firejail
	wicd
	xscreensaver
	xserver-xorg-video-all
	x11vnc
	xtightvncviewer
)


purge_packages+=(
	libsystemd0
)



# i386
#custom_deb_packages+=(yad_0.27.0-1_i386.deb palemoon_27.2.0~repack-1_i386.deb)

# amd64
custom_deb_packages+=(yad_0.27.0-1_amd64.deb palemoon_27.2.0~repack-1_amd64.deb)

	

custom_deb_packages+=(
	firemenu-1.2.deb
	live-config-refracta_0.0.5.deb
	refracta-lang_1.1.deb
	refracta2usb-2.3.6.deb
	refractainstaller-base_9.2.1_all.deb
	refractainstaller-gui_9.2.1_all.deb
	refractasnapshot-base_10.0.2_all.deb
	refractasnapshot-gui_10.0.2_all.deb
	usbpmount-1.2+blend.deb
)
	
