#!/usr/bin/env zsh
# Copyright (c) 2016-2017 Dyne.org Foundation
# libdevuansdk is maintained by Ivan J. <parazyd@dyne.org>
#
# This file is part of libdevuansdk
#
# This source code is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this source code. If not, see <http://www.gnu.org/licenses/>.

## libdevuansdk configuration

vars+=(release version mirror section blend_name image_name vm_name)
vars+=(arch earch)
arrs+=(core_packages base_packages purge_packages blend_packages)

os="devuan"
release="jessie"
version="1.0.0-beta2"
mirror="http://auto.mirror.devuan.org/merged"
section="main"

image_name="${os}_${release}_${version}_${arch}"
[[ -n $blend_name  ]] && image_name="${image_name}_${blend_name}"
[[ -n $device_name ]] && image_name="${image_name}_${device_name}"

vm_name="${os}_${release}_${version}_${arch}_vagrant"
[[ -n $blend_name  ]] && vm_name="${image_name}_${blend_name}"

rootcredentials="root:toor"

core_packages=(
	acpi
	ca-certificates
	console-setup
	busybox
	busybox-syslogd
	discover
	gettext-base
	initramfs-tools
	installation-report
	kbd
	keyboard-configuration
	klibc-utils
	laptop-detect
	linux-base
	locales
	pciutils
	reportbug
	ucf
	usbutils
	xkb-data
	e2fsprogs
	bzip2
	curl
	less
	vim
	nano
	sysvinit
)

base_packages=(
	$grubversion
	apt-utils
	aptitude
	bash-completion
	bind9-host
	bsd-mailx
	debian-faq
	debian-faq
	dnsutils
	doc-debian
	exim4
	ftp
	hdparm
	mlocate
	mutt
	ncurses-term
	nfs-common
	openssh-client
	procmail
	rpcbind
	telnet
	texinfo
	w3m
	whois
	xz-utils
	parted
	openssh-client
	sudo
	alsa-utils
	mawk
	wpasupplicant
	wireless-tools
	firmware-linux-free
	rsync
	lvm2
	cryptsetup
	unzip
)

purge_packages+=(
)
