#!/usr/bin/env zsh
# Copyright (c) 2016-2017 Dyne.org Foundation
# libdevuansdk is maintained by Ivan J. <parazyd@dyne.org>
#
# This file is part of libdevuansdk
#
# This source code is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this source code. If not, see <http://www.gnu.org/licenses/>.

## libdevuansdk configuration

vars+=(release version mirror section blend_name image_name vm_name)
vars+=(arch earch)

arrs+=(core_packages base_packages purge_packages blend_packages)


os="devuan"
release="jessie"
version="1.0.0-beta2+"
mirror="http://auto.mirror.devuan.org/merged"
section="main"

image_name="${os}_${release}_${version}_${arch}"
[[ -n "$blend_name"  ]] && image_name="${image_name}_${blend_name}"
[[ -n "$device_name" ]] && image_name="${image_name}_${device_name}"

vm_name="${os}_${release}_${version}_${arch}_vagrant"
[[ -n $blend_name  ]] && vm_name="${image_name}_${blend_name}"

rootcredentials="root:toor"
usercredentials="devuan:devuan"

core_packages=(
	ca-certificates
	initramfs-tools
	bzip2
	curl
	vim
	lsof
	bash-completion
	texinfo

)

base_packages=(
	acpi-support-base
	aptitude
	apt-listchanges
	discover
	dnsutils
	doc-debian
	docutils-common
	docutils-doc
	ftp
	gettext
	gnupg2
	grub-pc
	laptop-detect
	mlocate
	mutt
	ncurses-term
	nfs-common
	openssh-client
	procmail
	rsyslog
	telnet
	usbutils
	whois
	task-desktop
	task-english
	locales
#	locales-all
	task-xfce-desktop
	task-print-server
	tasksel
	tasksel-data
	w3m
)

purge_packages+=(

)
