#!/usr/bin/env zsh
# config for simple-ice.blend


vars+=(username userpass default_shell i386flavor)
#arrs+=(custom_deb_packages)

blend_name="simple-ice"
blend_vers="1.0"

image_name="${blend_name}-${blend_vers}-${arch}"

os="$blend_name"
release="jessie"

username="user"
userpass="user"
default_shell="/bin/bash"
#rootcredentials="root:some-other-password"



extra_packages+=(

	grub-pc
	lsof
	bash-completion
	texinfo
	acpi-support-base
	aptitude
	apt-listchanges
	discover
	dnsutils
	doc-debian
	docutils-common
	docutils-doc
	ftp
	gettext
	gnupg2
	laptop-detect
	mlocate
	mutt
	ncurses-term
	nfs-common
	procmail
	reportbug
	telnet
	usbutils
	w3m
	whois
	xorg
	xserver-xorg-video-all
	xterm
	spacefm
	icewm
	leafpad
	lightdm
	pmount
)

